import { FaReact, FaJs, FaCss3Alt, FaNodeJs } from "react-icons/fa";
import {
  SiTypescript,
  SiRedux,
  SiTailwindcss,
  SiSocketdotio,
  SiGraphql,
  SiFirebase,
  SiMui,
  SiAntdesign,
  SiChakraui,
} from "react-icons/si";

export const skillsData = [
  {
    id: 1,
    category: "Frontend Core",
    skills: [
      {
        name: "React.js",
        icon: FaReact,
        color: "#61DAFB",
        level: "expert",
        stars: 5,
        experience: "2+ years",
        description: "Building scalable SPAs",
      },
      {
        name: "JavaScript ES6+",
        icon: FaJs,
        color: "#F7DF1E",
        level: "expert",
        stars: 4.5,
        experience: "2+ years",
        description: "Modern JS patterns",
      },
      {
        name: "TypeScript",
        icon: SiTypescript,
        color: "#3178C6",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Type-safe development",
      },
      {
        name: "HTML5 & CSS3",
        icon: FaCss3Alt,
        color: "#1572B6",
        level: "expert",
        stars: 5,
        experience: "2+ years",
        description: "Semantic & accessible",
      },
    ],
  },
  {
    id: 2,
    category: "State Management",
    skills: [
      {
        name: "Redux Toolkit",
        icon: SiRedux,
        color: "#764ABC",
        level: "advanced",
        stars: 4.5,
        experience: "2+ years",
        description: "Global state management",
      },
      {
        name: "React Query",
        icon: null,
        color: "#FF4154",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Server state handling",
      },
      {
        name: "Zustand",
        icon: null,
        color: "#08D665",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Lightweight state",
      },
      {
        name: "Context API",
        icon: FaReact,
        color: "#61DAFB",
        level: "expert",
        stars: 5,
        experience: "2+ years",
        description: "React state sharing",
      },
    ],
  },
  {
    id: 3,
    category: "UI & Styling",
    skills: [
      {
        name: "Tailwind CSS",
        icon: SiTailwindcss,
        color: "#06B6D4",
        level: "expert",
        stars: 5,
        experience: "2+ years",
        description: "Utility-first styling",
      },
      {
        name: "Material-UI",
        icon: SiMui,
        color: "#007FFF",
        level: "advanced",
        stars: 4.5,
        experience: "2+ years",
        description: "Component library",
      },
      {
        name: "Ant Design",
        icon: SiAntdesign,
        color: "#1890FF",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Enterprise UI",
      },
      {
        name: "Chakra UI",
        icon: SiChakraui,
        color: "#319795",
        level: "advanced",
        stars: 4.5,
        experience: "1+ year",
        description: "Accessible components",
      },
    ],
  },
  {
    id: 4,
    category: "APIs & Integration",
    skills: [
      {
        name: "REST APIs",
        icon: null,
        color: "#08D665",
        level: "expert",
        stars: 5,
        experience: "2+ years",
        description: "RESTful services",
      },
      {
        name: "GraphQL",
        icon: SiGraphql,
        color: "#E10098",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Query language",
      },
      {
        name: "Socket.io",
        icon: SiSocketdotio,
        color: "#010101",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Real-time communication",
      },
      {
        name: "Axios",
        icon: null,
        color: "#5A29E4",
        level: "expert",
        stars: 5,
        experience: "2+ years",
        description: "HTTP client",
      },
    ],
  },
  {
    id: 5,
    category: "Tools & Services",
    skills: [
      {
        name: "Firebase",
        icon: SiFirebase,
        color: "#FFCA28",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Auth & database",
      },
      {
        name: "Stripe",
        icon: null,
        color: "#635BFF",
        level: "advanced",
        stars: 4,
        experience: "1+ year",
        description: "Payment integration",
      },
      {
        name: "Git & GitHub",
        icon: null,
        color: "#F05032",
        level: "expert",
        stars: 5,
        experience: "2+ years",
        description: "Version control",
      },
      {
        name: "Node.js",
        icon: FaNodeJs,
        color: "#339933",
        level: "intermediate",
        stars: 3.5,
        experience: "6+ months",
        description: "Backend basics",
      },
    ],
  },
];