import { image } from "../../assets/image";

export const Practice = [
  {
    id: 1,
    title: "Quran App",
    bgImg: image.pf1,
    desc: "Immersive Quranic experience with audio controls, surah navigation, and elegant Arabic typography. Features play/pause controls and seamless API integration for authentic recitations.",
    tags: ["React.js", "REST API", "Audio Player", "Islamic App", "Responsive"],
    featured: true,
    githubLink: "https://github.com/ayeshasikander/Quran_Majeed_App.git",
    liveLink: "https://quran-ul-kareem.netlify.app/",
  },
  {
    id: 2,
    title: "Green-Book Library",
    bgImg: image.pf2,
    desc: "Digital book discovery platform with advanced search, detailed book previews, and intuitive card-based UI. Leverages open-source API for comprehensive book database.",
    tags: [
      "React.js",
      "API Integration",
      "Search",
      "Material-UI",
      "Responsive",
    ],
    featured: true,
    githubLink: "https://github.com/ayeshasikander/Green_Books.git",
    liveLink: "https://green-books.vercel.app/",
  },
  {
    id: 3,
    title: "Rejouice Clone",
    bgImg: image.pf3,
    desc: "Pixel-perfect recreation of Rejouice's award-winning design. Features smooth scroll animations, parallax effects, and advanced GSAP timeline sequences.",
    tags: ["HTML5", "CSS3", "JavaScript", "GSAP", "Animation"],
    featured: false,
    githubLink: "https://github.com/ayeshasikander/Rejouice-clone.git",
    liveLink: "https://rejouice-clone.netlify.app/",
  },
  {
    id: 4,
    title: "Radiologex Platform",
    bgImg: image.pf4,
    desc: "Professional healthcare platform for radiology services. Built with React.js featuring appointment booking, service listings, and responsive medical UI components.",
    tags: ["React.js", "Healthcare", "UI/UX", "Responsive", "Professional"],
    featured: true,
    githubLink: "https://github.com/ayeshasikander/radiologex.git",
    liveLink: "https://radiologex-cl.netlify.app/",
  },
  {
    id: 5,
    title: "FlickFlex Streaming",
    bgImg: image.pf5,
    desc: "Netflix-inspired streaming platform with Firebase authentication, TMDB API integration, dynamic content filtering, and personalized user experience.",
    tags: ["React.js", "Firebase", "Authentication", "TMDB API", "Redux"],
    featured: true,
    githubLink: "https://github.com/ayeshasikander/Netflix-Clone.git",
    liveLink: "https://flickflex.netlify.app/",
  },
  {
    id: 6,
    title: "View Complete Portfolio",
    desc: "Explore my comprehensive collection of 20+ projects on GitHub. Including open-source contributions, experimental projects, and production applications across various domains.",
    tags: ["GitHub", "Portfolio", "Open Source", "Full Stack", "React.js"],
    featured: false,
    githubLink: "https://github.com/ayeshasikander",
    liveLink: "",
  },
];
